### ISSUE TITLE
Compare to https://github.com/google/licenseclassifier (at least)

### ISSUE THREAD

**Issue by dgryski** [src-d/go-license-detector#11]
There seem to be a number of other license classifiers out there.  How do they compare?

**Comment by vmarkovtsev** [comment]
Thanks for pointing at the Google one! It was hard to google hehe.  Yep, the comparison is necessary, we will add it.

**Comment by bzz** [comment]
Nice find, @dgryski thank you for sharing!

@vmarkovtsev btw, do you think it may be worth adding this topic to GH repository https://github.com/topics/license-management ?

**Comment by vmarkovtsev** [comment]
licenseclassifier's result on our dataset is 84% (802 out of 902). I think we are going to re-use some of the code from it - it plays nicely with multiple licenses.
