### ISSUE TITLE
Add comparison to few other tools for license detection

### ISSUE THREAD

**Issue by bzz** [src-d/go-license-detector#35]
On top of the awesome list that already exists in https://github.com/src-d/go-license-detector#quality it would be nice to include numbers for:

 - ✅ https://github.com/benbalter/licensee, Ruby
 - ✅ https://github.com/google/licenseclassifier, Go
 - ✅ https://github.com/boyter/lc, Go
 - https://github.com/amzn/askalono, Rust
 - LiD https://source.codeaurora.org/external/qostg/lid, Python

add a .sh script to reproduce those measurements, sort the resulting table i.e by detection rate and may be add a programming language column.

**Comment by vmarkovtsev** [comment]
Fixed https://github.com/src-d/go-license-detector#quality
