### ISSUE TITLE
gomodules: impossible to build when depend on gopkg.in/src-d/go-license-detector.v2

### ISSUE THREAD

**Issue by sweetca** [src-d/go-license-detector#48]
Hello src-d team
@vmarkovtsev please help to solve issue
Right now Im using gopkg.in/src-d/go-license-detector.v2 as my dependency
Currently not possible to pass build when using gomodules because of incorrect dependencies in your go.mod source:
https://github.com/src-d/go-license-detector/blob/9f8957ebb540649fbb811e4d5925f162e333716b/go.mod#L40
blackfriday does not host v2.0.0 anymore
https://gopkg.in/russross/blackfriday.v2
Is it possible to update go-license-detector with v.2.0.1 ?

**Comment by vmarkovtsev** [comment]
Fixed in gld v2.0.1

**Comment by sweetca** [comment]
@vmarkovtsev Thanks a lot, Vadim

**Comment by RodsAlex** [comment]
Hi,
I can't build on my side because in go.mod there is github.com/russross/blackfriday/v2 v2.0.1 instead of github.com/russross/blackfriday.v2 v2.0.1
Is it possible to fix it ?
Thank you for you help.

**Comment by vmarkovtsev** [comment]
@RodsAlex can you please PR the fix?
