### ISSUE TITLE
Build failure -- How to build?

### ISSUE THREAD

**Issue by prologic** [src-d/go-license-detector#50]
Trying to build this from source fails:

```
~/Contributions/go-license-detector
 (master) 0
$ GOPROXY="" go build .
can't load package: package gopkg.in/src-d/go-license-detector.v2: unknown import path "gopkg.in/src-d/go-license-detector.v2": cannot find module providing package gopkg.in/src-d/go-license-detector.v2
```

How do you build this? I can see you *are* using Go modules but for some reason the import path defined in your `go.mod` `go build` can't find :/ wut?!

**Comment by vmarkovtsev** [comment]
Weird, CI passes: https://github.com/src-d/go-license-detector/blob/11a13ac1c798b8b0547b0362135867a71dcd8389/.travis.yml#L18
