### ISSUE TITLE
Return matching license files

### ISSUE THREAD

**Issue by adracus** [src-d/go-license-detector#55]
Currently, the result of both `Detect` and `Analyse` return only a mapping from `spdix` license id to a confidence in form of a `float32`.

It would be awesome, if there was some way to see which file caused the highest probability of a certain license id. I'd use this feature for also referring a user to a path where the license can be found. Also, it'd simplify further postprocessing on the license such as e.g. extracting copyright information etc.

Btw: Love this library, keep up the good work!
If help is wanted on this issue, I can also have a look into it.

**Comment by vmarkovtsev** [comment]
Thanks for this proposal @adracus. Feel free to work on it, I will be happy to review and merge!
