### ISSUE TITLE
license for text

### ISSUE THREAD

**Issue by kellyp** [src-d/go-license-detector#57]
any reason not to resolve licenses from text in a public package?

**Comment by vmarkovtsev** [comment]
wdym text in a public package?

**Comment by kellyp** [comment]
sorry that was pre coffee.  I was thinking something like: https://github.com/kellyp/go-license-detector/blob/master/licensedb/analysis.go#L36

We need to be able to resolve licenses from text snippets and files.

**Comment by vmarkovtsev** [comment]
OK, so you suggest scanning source code file headers, right? Yeah, this is something nice to have, though nobody is working on it right now.

**Comment by kellyp** [comment]
Our use case consists of sending license files to a http service.  So we just chuck a bunch of text at the service and listen for a response with the list of licenses.  The filesystem doesn't factor in.  I think the example i provided would work for this.  thanks!

**Comment by vmarkovtsev** [comment]
I wonder if writing a custom [Filer](https://github.com/src-d/go-license-detector/blob/master/licensedb/filer/filer.go#L33) can work for you. You can make `ReadDir` always return a single key, and `ReadFile` return the real text for that artificial key.

**Comment by kellyp** [comment]
Oh sweet!  let me give that a go.  I think it may work.  It looks like it would fall through the dir check and go straight to the investigation!. thanks.

**Comment by kellyp** [comment]
It worked! thanks for your help.
