### ISSUE TITLE
gets stuck running the checker

### ISSUE THREAD

**Issue by lsoaresvw** [src-d/go-license-detector#73]
hey

At my project's root, I run:
```
export GO111MODULE=on
go mod download
go build -v gopkg.in/src-d/go-license-detector.v3/cmd/license-detector
./license-detector . --format json
```
but it stays there forever with output.. it looks blocked. is it supposed to take how long? it's a small project. thanks.

**Comment by vmarkovtsev** [comment]
@lsoaresvw What was the reason?

**Comment by lsoaresvw** [comment]
I don't know... I got an error before which doesn't happen now (I suspect because I suspended the computer after a long time). It's stuck again running.

`git:(master) ✗ ./license-detector .`
...
